server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
routes:
  - uri: /customers/{1}[1-9]+[0-9]*
    method: GET
    roles:
      - CLIENTE
  - uri: /customers/{1}[1-9]+[0-9]*
    method: PUT
    roles:
      - CLIENTE
  - uri: /customers/{1}[1-9]+[0-9]*
    method: DELETE
    roles:
      - CLIENTE
  - uri: /customers
    method: GET
    roles:
      - ADMIN
  - uri: /users/{1}[1-9]+[0-9]*/password
    method: PATCH
    roles:
      - CLIENTE
  - uri: /products
    method: POST
    roles:
      - ADMIN
  - uri: /invoices
    method: GET
    roles:
      - ADMIN
  - uri: /invoices/customer/{1}[1-9]+[0-9]*
    method: GET
    roles:
      - CLIENTE
  - uri: /invoices
    method: POST
    roles:
      - CLIENTE
