spring:
  application:
   name: auth
  config:
    import: configserver:http://localhost:8081
  cloud:
    config:
      username: root
      password: s3cr3t

routes-protected:
  routes:
    - uri: /customers/{1}[1-9]+[0-9]*
      method: GET
      roles:
        - CLIENTE
    - uri: /customers/{1}[1-9]+[0-9]*
      method: PUT
      roles:
        - CLIENTE
    - uri: /customers/{1}[1-9]+[0-9]*
      method: DELETE
      roles:
        - CLIENTE
    - uri: /customers
      method: GET
      roles:
        - ADMIN
    - uri: /users/{1}[1-9]+[0-9]*/password
      method: PATCH
      roles:
        - CLIENTE
    - uri: /products
      method: POST
      roles:
        - ADMIN
    - uri: /invoices
      method: GET
      roles:
        - ADMIN
    - uri: /invoices/customer/{1}[1-9]+[0-9]*
      method: GET
      roles:
        - CLIENTE
    - uri: /invoices
      method: POST
      roles:
        - CLIENTE
