
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/comidev/comistore-microservices.git
          searchPaths: config-data
          defaultLabel: master
  security:
    user:
      name: root
      password: s3cr3t
